### ISSUE TITLE
How to send ou list of Rooms upon registration?

### ISSUE THREAD

**Issue by k0fi** [jeroendk/go-vuejs-chat#1]
Hello,
I could not figure out how should I send back list of public rooms available after a user is logged in/registered. 
This is very realistic scenario for a real chatroom because users don't know by heart what rooms are available. 
So appreciate your help.

**Comment by jeroendk** [comment]
Hi!

Since a chatServer instance only loads a room when requested, I think you should provide a list of rooms by creating an API endpoint. 

Add something like this to your main.go or a dedicated handler.
```
roomRepo := &repository.RoomRepository{Db: db}

http.HandleFunc("/api/rooms", func(w http.ResponseWriter, r *http.Request) {
    rooms := roomRepo.getAllPublicRooms()
    json.NewEncoder(w).Encode(rooms)
})

```
Then implement the getAllPublicRooms method in the repo class.

If you want to use the Websocket connection you need to do something similar because, as I mentioned, the chatServer does not always know all the rooms. If you only run a single instance, then it will know all the current rooms. In that case you can encode the chatServer.rooms map in a Message and send it to the client.
